### ISSUE TITLE
Comment Style in Vignettes

### ISSUE THREAD

**Issue by discoleo** [mikeblazanin/gcplyr#113]
# Comment Style in Vignettes

Insert a space between the "#" comment tag and the first word following it. The lack of space makes the comments difficult to read at low resolution (e.g. pdf-file fit in page) or in streamed presentations.

Improved readability:
	# This code was previously explained.
	# Here we're re-running it so it's available for us to work with.
	# <= notice the space before the 1st word;

**Comment by mikeblazanin** [comment]
done in v1.1.0.9000 (will be included in next release)
