### ISSUE TITLE
Refactoring Code: Split file functions.R

### ISSUE THREAD

**Issue by discoleo** [mikeblazanin/gcplyr#135]
# Refactoring Code

The code in functions.R should be split across multiple files based on purpose of the respective functions, e.g.:
- Utilities.R (or Tools.R or Helper.R): functions used as (mostly) internal/non-specific utility/helper functions;
- Import.R: functions to read/import data;
- Export.R: functions to write/export data;
- Transform.R: functions for various conversions;
- Analyse.R: functions used to analyse the data;

**Comment by mikeblazanin** [comment]
partially done in v1.3.0.9000, no further changes are planned
