### ISSUE TITLE
[Man] make_designpattern: Example uses deprecated make_tidydesign

### ISSUE THREAD

**Issue by discoleo** [mikeblazanin/gcplyr#141]
# Man: make_designpattern

The example uses the deprecated make_tidydesign function:
   my_example <- make_tidydesign(nrows = 8, ncols = 12,
      design_element_name = make_designpattern(values = c("L", "G", "C"),
                                                rows = 2:7, cols = 2:11,
                                                pattern = "11223300",
                                                byrow = TRUE))

The manual does NOT explain the following details:
- the "0" pattern: it seems that NA are used;
- there seems to be some recycling of values, but neither it is clear how it is done, nor is it mentioned in the manual;

**Comment by mikeblazanin** [comment]
Fixed in v1.3.0.9000. Note that most documentation is in make_design; make_designpattern is simply a helper function with minimal documentation intentionally
